spring:
  datasource:
    url: jdbc:mysql://localhost:3306/modern_webpg?characterEncoding=utf8
    username: modern_webpg_05
    password: password
    driver-class-name: com.mysql.jdbc.Driver
client:
  url: http://localhost:63342